
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class usuario extends javax.swing.JFrame {

private ImageIcon im;
private Icon icono;
    public usuario() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.escala(jLabel2, "src/imagenes/usu.png");
        this.escala(jLabel1,"src/imagenes/morado.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        contraseña = new javax.swing.JPasswordField();
        usuariotext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 120, 170, 160);

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 28)); // NOI18N
        jLabel5.setText("Calculadora de Probabilidad");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 20, 430, 90);

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Ingresar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 500, 160, 50);

        contraseña.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        contraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        contraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(contraseña);
        contraseña.setBounds(240, 390, 170, 30);

        usuariotext.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jPanel1.add(usuariotext);
        usuariotext.setBounds(240, 320, 170, 40);

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 380, 170, 50);

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 320, 120, 40);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 480, 600);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 480, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String usu = usuariotext.getText();
    String contra = contraseña.getText();
    
    //JOptionPane.showMessageDialog(null,contr);
    
        if(usu.equals("umg")&& contra.equals("Solola@umg")){
        
          ventana1 ven = new ventana1();
          ven.setVisible(true);   
            dispose();
        }else{
            usuariotext.setText("");
            contraseña.setText("");
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }
    
    private void escala (JLabel imagen, String direccion){
       this.im =new ImageIcon(direccion);
       this.icono = new ImageIcon(
               this.im.getImage().getScaledInstance(
                       imagen.getWidth(), 
                       imagen.getHeight(), 
                       Image.SCALE_DEFAULT));
     imagen.setIcon(this.icono);
     this.repaint();
     
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuariotext;
    // End of variables declaration//GEN-END:variables
}
