
package ventanas;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import ventanas.ventana1;

public class ventana1 extends javax.swing.JFrame {
    private ImageIcon im;
    private Icon icono;
    int op[] = new int[11];
  
    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();
        this.setLocationRelativeTo(this);
        escala(jLabel14,"src/imagenes/free-blurry-background-1636594.jpg");
          //this.escala(teoremas, "src/imagenes/morado.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        te13 = new javax.swing.JLabel();
        te14 = new javax.swing.JLabel();
        te15 = new javax.swing.JLabel();
        te16 = new javax.swing.JLabel();
        te17 = new javax.swing.JLabel();
        te18 = new javax.swing.JLabel();
        te19 = new javax.swing.JLabel();
        te20 = new javax.swing.JLabel();
        ejemplo1 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        te4 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        te2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        defiición1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        te11 = new javax.swing.JLabel();
        te10 = new javax.swing.JLabel();
        te9 = new javax.swing.JLabel();
        te8 = new javax.swing.JLabel();
        te7 = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        dosa = new javax.swing.JTextField();
        tresa = new javax.swing.JTextField();
        cuatroa = new javax.swing.JTextField();
        cincoa = new javax.swing.JTextField();
        seisa = new javax.swing.JTextField();
        sietea = new javax.swing.JTextField();
        tres = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        unoa = new javax.swing.JTextField();
        resultado = new javax.swing.JTextField();
        mostrar = new javax.swing.JButton();
        tit = new javax.swing.JLabel();
        prueba = new javax.swing.JLabel();
        formula = new javax.swing.JLabel();
        te6 = new javax.swing.JLabel();
        te5 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        def = new javax.swing.JTextArea();
        te3 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        te1 = new javax.swing.JLabel();
        panelcalculadora = new javax.swing.JLabel();
        lhgds = new javax.swing.JScrollPane();
        ejem = new javax.swing.JTextArea();
        imejem = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(1170, 720));
        jFrame1.getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jRadioButton2.setText("jRadioButton1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(30, 660, 93, 23);

        te13.setBackground(new java.awt.Color(0, 0, 0));
        te13.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te13.setForeground(new java.awt.Color(0, 61, 35));
        te13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te13.setText("Teorema 12");
        te13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te13);
        te13.setBounds(0, 600, 170, 50);

        te14.setBackground(new java.awt.Color(0, 0, 0));
        te14.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te14.setForeground(new java.awt.Color(0, 61, 53));
        te14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te14.setText("Teorema 11");
        te14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te14);
        te14.setBounds(0, 550, 170, 50);

        te15.setBackground(new java.awt.Color(0, 0, 0));
        te15.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te15.setForeground(new java.awt.Color(0, 61, 53));
        te15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te15.setText("Teorema 10");
        te15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te15);
        te15.setBounds(0, 500, 170, 50);

        te16.setBackground(new java.awt.Color(0, 0, 0));
        te16.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te16.setForeground(new java.awt.Color(0, 61, 53));
        te16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te16.setText("Teorema 9");
        te16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te16);
        te16.setBounds(0, 450, 170, 50);

        te17.setBackground(new java.awt.Color(0, 0, 0));
        te17.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te17.setForeground(new java.awt.Color(0, 61, 53));
        te17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te17.setText("Teorema 8");
        te17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te17);
        te17.setBounds(0, 400, 170, 50);

        te18.setBackground(new java.awt.Color(0, 0, 0));
        te18.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te18.setForeground(new java.awt.Color(0, 61, 53));
        te18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te18.setText("Teorema 7");
        te18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te18);
        te18.setBounds(0, 350, 170, 50);

        te19.setBackground(new java.awt.Color(0, 0, 0));
        te19.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te19.setForeground(new java.awt.Color(0, 61, 53));
        te19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te19.setText("Teorema 6");
        te19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te19);
        te19.setBounds(0, 300, 170, 50);

        te20.setBackground(new java.awt.Color(0, 0, 0));
        te20.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te20.setForeground(new java.awt.Color(0, 61, 53));
        te20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te20.setText("Teorema 5");
        te20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te20);
        te20.setBounds(0, 250, 170, 50);

        ejemplo1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        ejemplo1.setForeground(new java.awt.Color(0, 102, 102));
        ejemplo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ejemplo1.setText("Un teorema es una proposición cuya verdad se demuestra.  En matemáticas, es toda proposición que partiendo de un  supuesto (hipótesis), afirma una racionabilidad (tesis) no  evidente por sí misma.1​  También puede decirse que un  teorema es una fórmula bien formada que puede ser  demostrada dentro de un sistema formal, partiendo  de axiomas u otros teoremas. Demostrar teoremas es un  asunto central en la lógica matemática. Los teoremas también  pueden ser expresados en lenguaje natural formalizado.");
        ejemplo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(ejemplo1);
        ejemplo1.setBounds(210, 430, 750, 240);

        t5.setBackground(new java.awt.Color(0, 0, 0));
        t5.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        t5.setForeground(new java.awt.Color(0, 61, 53));
        t5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t5.setText("Teorema 4");
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        t5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(t5);
        t5.setBounds(0, 200, 170, 50);

        te4.setBackground(new java.awt.Color(0, 0, 0));
        te4.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te4.setForeground(new java.awt.Color(0, 61, 53));
        te4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te4.setText("Teorema 3");
        te4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(te4);
        te4.setBounds(0, 150, 170, 50);

        t3.setBackground(new java.awt.Color(0, 0, 0));
        t3.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        t3.setForeground(new java.awt.Color(0, 61, 53));
        t3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t3.setText("Teorema 2");
        t3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        t3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(t3);
        t3.setBounds(0, 100, 170, 50);

        te2.setBackground(new java.awt.Color(0, 0, 0));
        te2.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te2.setForeground(new java.awt.Color(0, 61, 53));
        te2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te2.setText("Teorema 1");
        te2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te2MouseClicked(evt);
            }
        });
        jPanel2.add(te2);
        te2.setBounds(0, 50, 170, 50);

        jLabel16.setBackground(new java.awt.Color(204, 0, 0));
        jLabel16.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("Ejemplo");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(210, 390, 90, 40);

        jLabel4.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Definición");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 90, 90, 40);

        titulo1.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 102, 102));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(titulo1);
        titulo1.setBounds(450, 20, 350, 70);

        defiición1.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        defiición1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defiición1.setText("Un teorema es una proposición cuya verdad se demuestra.  En matemáticas, es toda proposición que partiendo de un  supuesto (hipótesis), afirma una racionabilidad (tesis) no  evidente por sí misma.1​  También puede decirse que un  teorema es una fórmula bien formada que puede ser  demostrada dentro de un sistema formal, partiendo  de axiomas u otros teoremas. Demostrar teoremas es un  asunto central en la lógica matemática. Los teoremas también  pueden ser expresados en lenguaje natural formalizado.");
        defiición1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(defiición1);
        defiición1.setBounds(210, 130, 750, 240);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Teoremas");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 170, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/free-blurry-background-1636594.jpg"))); // NOI18N
        jLabel17.setText("jLabel14");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(-170, 0, 1150, 700);

        jFrame1.getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 700);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 740));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        te11.setBackground(new java.awt.Color(0, 0, 0));
        te11.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te11.setForeground(new java.awt.Color(0, 61, 53));
        te11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te11.setText("Teorema 11");
        te11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te11MouseClicked(evt);
            }
        });
        jPanel1.add(te11);
        te11.setBounds(10, 580, 170, 50);

        te10.setBackground(new java.awt.Color(0, 0, 0));
        te10.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te10.setForeground(new java.awt.Color(0, 61, 53));
        te10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te10.setText("Teorema 10");
        te10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te10MouseClicked(evt);
            }
        });
        jPanel1.add(te10);
        te10.setBounds(10, 530, 170, 50);

        te9.setBackground(new java.awt.Color(0, 0, 0));
        te9.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te9.setForeground(new java.awt.Color(0, 61, 53));
        te9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te9.setText("Teorema 9");
        te9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te9MouseClicked(evt);
            }
        });
        jPanel1.add(te9);
        te9.setBounds(10, 480, 170, 50);

        te8.setBackground(new java.awt.Color(0, 0, 0));
        te8.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te8.setForeground(new java.awt.Color(0, 61, 53));
        te8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te8.setText("Teorema 8");
        te8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te8MouseClicked(evt);
            }
        });
        jPanel1.add(te8);
        te8.setBounds(10, 430, 170, 50);

        te7.setBackground(new java.awt.Color(0, 0, 0));
        te7.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te7.setForeground(new java.awt.Color(0, 61, 53));
        te7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te7.setText("Teorema 7");
        te7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te7MouseClicked(evt);
            }
        });
        jPanel1.add(te7);
        te7.setBounds(10, 380, 170, 50);

        uno.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 102, 0));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(uno);
        uno.setBounds(990, 260, 150, 40);

        dos.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        dos.setForeground(new java.awt.Color(102, 0, 102));
        dos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(dos);
        dos.setBounds(990, 310, 150, 40);

        cinco.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        cinco.setForeground(new java.awt.Color(51, 51, 51));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cinco);
        cinco.setBounds(990, 460, 150, 40);

        seis.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        seis.setForeground(new java.awt.Color(0, 153, 153));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(seis);
        seis.setBounds(990, 520, 150, 40);

        siete.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        siete.setForeground(new java.awt.Color(204, 204, 0));
        siete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(siete);
        siete.setBounds(990, 560, 150, 40);

        dosa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        dosa.setForeground(new java.awt.Color(102, 0, 102));
        dosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosaActionPerformed(evt);
            }
        });
        jPanel1.add(dosa);
        dosa.setBounds(1150, 310, 80, 40);

        tresa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        tresa.setForeground(new java.awt.Color(0, 153, 0));
        tresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresaActionPerformed(evt);
            }
        });
        jPanel1.add(tresa);
        tresa.setBounds(1150, 360, 80, 40);

        cuatroa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        cuatroa.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(cuatroa);
        cuatroa.setBounds(1150, 410, 80, 40);

        cincoa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        cincoa.setForeground(new java.awt.Color(51, 51, 51));
        cincoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoaActionPerformed(evt);
            }
        });
        jPanel1.add(cincoa);
        cincoa.setBounds(1150, 460, 80, 40);

        seisa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        seisa.setForeground(new java.awt.Color(0, 153, 153));
        seisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisaActionPerformed(evt);
            }
        });
        jPanel1.add(seisa);
        seisa.setBounds(1150, 510, 80, 40);

        sietea.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        sietea.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.add(sietea);
        sietea.setBounds(1150, 560, 80, 40);

        tres.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        tres.setForeground(new java.awt.Color(0, 153, 0));
        tres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(tres);
        tres.setBounds(990, 360, 150, 40);

        cuatro.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 0, 0));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cuatro);
        cuatro.setBounds(990, 410, 150, 40);

        unoa.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        unoa.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.add(unoa);
        unoa.setBounds(1150, 260, 80, 40);

        resultado.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(resultado);
        resultado.setBounds(990, 620, 290, 40);

        mostrar.setBackground(new java.awt.Color(0, 204, 0));
        mostrar.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        mostrar.setForeground(new java.awt.Color(0, 102, 102));
        mostrar.setText("Calcular");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar);
        mostrar.setBounds(1070, 670, 120, 37);

        tit.setFont(new java.awt.Font("Georgia", 2, 36)); // NOI18N
        tit.setForeground(new java.awt.Color(0, 204, 0));
        tit.setText("Calculadora");
        jPanel1.add(tit);
        tit.setBounds(1040, 50, 210, 40);

        prueba.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        prueba.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prueba.setText("Fórmula");
        jPanel1.add(prueba);
        prueba.setBounds(970, 110, 130, 30);

        formula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(formula);
        formula.setBounds(970, 140, 310, 110);

        te6.setBackground(new java.awt.Color(0, 0, 0));
        te6.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te6.setForeground(new java.awt.Color(0, 61, 53));
        te6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te6.setText("Teorema 6");
        te6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te6MouseClicked(evt);
            }
        });
        jPanel1.add(te6);
        te6.setBounds(10, 330, 170, 50);

        te5.setBackground(new java.awt.Color(0, 0, 0));
        te5.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te5.setForeground(new java.awt.Color(0, 61, 53));
        te5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te5.setText("Teorema 5");
        te5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te5MouseClicked(evt);
            }
        });
        jPanel1.add(te5);
        te5.setBounds(10, 280, 170, 50);

        t4.setBackground(new java.awt.Color(0, 0, 0));
        t4.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        t4.setForeground(new java.awt.Color(0, 61, 53));
        t4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t4.setText("Teorema 4");
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        t4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t4MouseClicked(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(10, 230, 170, 50);

        def.setEditable(false);
        def.setColumns(20);
        def.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        def.setRows(5);
        jScrollPane1.setViewportView(def);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 110, 750, 190);

        te3.setBackground(new java.awt.Color(0, 0, 0));
        te3.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te3.setForeground(new java.awt.Color(0, 61, 53));
        te3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te3.setText("Teorema 3");
        te3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te3MouseClicked(evt);
            }
        });
        jPanel1.add(te3);
        te3.setBounds(10, 180, 170, 50);

        t2.setBackground(new java.awt.Color(0, 0, 0));
        t2.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        t2.setForeground(new java.awt.Color(0, 61, 53));
        t2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t2.setText("Teorema 2");
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        t2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(10, 130, 170, 50);

        te1.setBackground(new java.awt.Color(0, 0, 0));
        te1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        te1.setForeground(new java.awt.Color(0, 61, 53));
        te1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        te1.setText("Teorema 1");
        te1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        te1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        te1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                te1MouseClicked(evt);
            }
        });
        jPanel1.add(te1);
        te1.setBounds(10, 80, 170, 50);

        panelcalculadora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel1.add(panelcalculadora);
        panelcalculadora.setBounds(960, 30, 330, 690);

        lhgds.setBackground(new java.awt.Color(0, 255, 51));

        ejem.setEditable(false);
        ejem.setColumns(20);
        ejem.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        ejem.setRows(5);
        lhgds.setViewportView(ejem);

        jPanel1.add(lhgds);
        lhgds.setBounds(200, 340, 750, 190);
        jPanel1.add(imejem);
        imejem.setBounds(260, 530, 610, 190);

        jLabel15.setBackground(new java.awt.Color(204, 0, 0));
        jLabel15.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("Ejemplo");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(200, 300, 90, 40);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Georgia", 2, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 660, 120, 40);

        jLabel3.setFont(new java.awt.Font("Georgia", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Definición");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 70, 90, 40);

        titulo.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 102, 102));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo);
        titulo.setBounds(450, 20, 350, 70);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Teoremas");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 170, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/free-blurry-background-1636594.jpg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(-170, 0, 1470, 740);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1300, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void te1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te1MouseClicked
       titulo.setText("Teorema 1");
       def.setText("\n  El número de permutaciones de n objetos es n!\n "
               + "\n  Este teorema nos ayuda a calcular de cuantas formas distintas "
               + "\n se pueden ordenar n elementos. ");
       ejem.setText("\n Juan, Susana y María van a la tienda, en donde solo atienden"
               + "\n una persona a la vez ¿De cuántas formas pueden ser atendidos?"
               + "\n\n  Datos."
               + "\n    n = 3");
       
       this.escala(imejem, "src/imres/teo1.png");
       this.escala(formula,"src/formulas/f1.png");
       uno.setText(" n ");
       unoa.setText("");
       dos.setVisible(false);    dosa.setVisible(false);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       
       activar(0);
    }//GEN-LAST:event_te1MouseClicked

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void te2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_te2MouseClicked

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
       titulo.setText(" Teorema 2");
       def.setText(" El número de permutaciones de n elementos distintos"
               + "\n tomados de r a la vez."
               + "\n\n    nPr = n!/(n-r)!"
               + "\n\n Con este teorema podemos calcular la cantidad de formas "
               + "\n distintas en las que se pueden ordenar una cantidad específica "
               + "\n de elementos pertenecientes a un conjunto n, donde n es el la"
               + "\n cantidad total de elementos y r es el número de elementos a "
               + "\n ordenar.");
       
       ejem.setText(" \nMaría, Ester, Sofía, Mónica y Melissa quieren ir al dentista"
               + "\n  este sábado, pero ya solo hay cupo para tres personas. "
               + "\n ¿Calcule la cantidad de formas en que pueden utilizar para "
               + "\n reservar cita a las tres personas. "
               + "\n\n  Datos."
               + "\n    n = 5"
               + "\n    r = 3");
              this.escala(imejem, "src/imres/teo2.png");
              this.escala(formula, "src/formulas/f2.png");
              uno.setText(" n ");
              dos.setText(" r ");
              unoa.setText("");
              dosa.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(1);
    }//GEN-LAST:event_t2MouseClicked

    private void te3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te3MouseClicked
       titulo.setText("Teorema 3");
       def.setText("\n El número de permutaciones de n objetos ordenados en un"
               + "\n circulo es: "
               + "\n\n          P = (n-1)!\n"
               + "\n Con este teorema podemos calcular las formas posibles para "
               + "\n ordenar n elementos en una forma circualar, alrededor de "
               + "\n una mesa, alrededor de una fogata etc.  ");
       ejem.setText("\n ¿De cuantas maneras se pueden sentar seis amigos al rededor"
               + "\n de una fogata?"
               + "\n\n  Datos."
               + "\n    n = 6");
              this.escala(imejem, "src/imres/teo3.png");
              this.escala(formula, "src/formulas/f3.png");
              uno.setText(" n ");
              unoa.setText("");
       dos.setVisible(false);    dosa.setVisible(false);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(2);
    }//GEN-LAST:event_te3MouseClicked

    private void t4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MouseClicked
        titulo.setText("Teorema 4");
        def.setText("\n El número de permutaciones distintas de n elementos,"
                + "\n en el que n1 son elementos de un tipo, n2 de otro y nk de otro."
                + "\n\n               P = n!/n1!*n2!...*nk!\n"
                + "\n Con este teoremas podemos calcular de cuantas formas se "
                + "\n pueden ordenar n elementos totales, tomando en cuanta que hay"
                + "\n elementos repetidos o de una misma clase.  ");
        ejem.setText("\n ¿De cuantas formas podemos ordenar las letras"
                + "\n de la palabra BANANA"
                + "\n\n  Datos."
                + "\n    n = 6"
                + "\n    n1 = 1 "
                + "\n    n2 = 3 "
                + "\n    n3 = 2 ");
               this.escala(imejem, "src/imres/teo4.png");
               this.escala(formula, "src/formulas/f4.png");
               uno.setText(" n "); unoa.setText("");
               dos.setText(" n1 "); dosa.setText("");
               tres.setText(" n2 "); tresa.setText("");
               cuatro.setText(" n3 "); cuatroa.setText("");
               cinco.setText(" n4 "); cincoa.setText("");
               seis.setText(" n5 "); seisa.setText("");
               siete.setText(" n6 "); sietea.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(true);   tresa.setVisible(true);
       cuatro.setVisible(true); cuatroa.setVisible(true);
       cinco.setVisible(true);  cincoa.setVisible(true);
       seis.setVisible(true);   seisa.setVisible(true);
       siete.setVisible(true);  sietea.setVisible(true);
       activar(3);
    }//GEN-LAST:event_t4MouseClicked

    private void te5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te5MouseClicked
       titulo.setText(" Teorema 5");
       def.setText(" \n El número de formas de partir un conjunto de n elementos en r "
               + "\n celdas, con n1 elmenentos en la primera celda, n2 en la segunda, "
               + "\n hasta nk."
               + "\n\n        P = n!/n1!*n2!...nk!\n"
               + "\n Este teorema es similar al teorema 4, salvo que en este teorema "
               + "\n agrupamos los elementos en celdas de n elmentos sin importar si "
               + "\n son iguales o no. ");
       ejem.setText("\n De las letras A,B,C,D,E,F. ¿en cuantas formas las podemos "
               + "\nordenar en grupos dado que el primer grupo contenga 3 elementos,"
               + "\n la segunda 2 elementos y la tercero 1."
               + "\n\n  Datos."
               + "\n    n = 6"
               + "\n    n1 = 1"
               + "\n    n2 = 3"
               + "\n    n3 = 2");
       this.escala(imejem, "src/imres/teo4.png");
       this.escala(formula, "src/formulas/f4.png");
       uno.setText(" n ");unoa.setText("");
               dos.setText(" n1 "); dosa.setText("");
               tres.setText(" n2 "); tresa.setText("");
               cuatro.setText(" n3 "); cuatroa.setText("");
               cinco.setText(" n4 "); cincoa.setText("");
               seis.setText(" n5 "); seisa.setText("");
               siete.setText(" n6 "); sietea.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(true);   tresa.setVisible(true);
       cuatro.setVisible(true); cuatroa.setVisible(true);
       cinco.setVisible(true);  cincoa.setVisible(true);
       seis.setVisible(true);   seisa.setVisible(true);
       siete.setVisible(true);  sietea.setVisible(true);
       activar(4);
    }//GEN-LAST:event_te5MouseClicked

    private void te6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te6MouseClicked
      titulo.setText("Teorema 6");
      def.setText("\n El número de combinaciones de n elementos distintos tomados "
              + "\n de r a la vez:"
              + "\n\n            P = (n/r) = n!/r!(n-r)!\n"
              + "\n Este teorema nos ayuda a calcular la probabilidad de escoger r "
              + "\n elementos de un conjunto de n elementos.");
      ejem.setText("\n Se necesita escoger a 3 estudiantes de un grupo de 5,"
              + "\n para actuar de obejas en una obra, ¿De cuantas formas se podrian"
              + "\n escoger a los 3 estudiantes"
              + "\n\n Datos."
              + "\n   n = 5"
              + "\n   r = 3");
      this.escala(imejem, "src/imres/teo6.png");
      this.escala(formula, "src/formulas/f6.png");
      uno.setText(" n "); unoa.setText("");
              dos.setText(" r "); dosa.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(5);
    }//GEN-LAST:event_te6MouseClicked

    private void te7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te7MouseClicked
    titulo.setText("Teorema 7");
    def.setText("\n Si A y B son dos eventos entonces:"
            + "\n\n         P(AUB) = P(A) + P(B) - P(AnB)\n"
            + "\n Este teorema nos ayuda a calcular la unión de dos eventos por "
            + "\n medio de sus probabilidades.");
    ejem.setText("\n En una ciudad el 85% de los niños les gusta jugar futbol"
            + "\n y el 75% basket. Si el 95% de los niños les gusta ambos deportes"
            + "\n ¿Calcule la probabilidad de escoger a un niño que le guste "
            + "\n alguno de estos deportes."
            + "\n\n  Datos."
            + "\n    P(A) = 0.85"
            + "\n    P(B) = 0.75"
            + "\n    P(AnB) 0.95");
    this.escala(imejem, "src/imres/TEO7.png");
    this.escala(formula, "src/formulas/f7.png");
              uno.setText(" P(A) "); unoa.setText("");
              dos.setText(" P(B) "); dosa.setText("");
              tres.setText("-P(AnB)"); tresa.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(true);   tresa.setVisible(true);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(6);
    }//GEN-LAST:event_te7MouseClicked

    private void te8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te8MouseClicked
        titulo.setText("Teorema 8");
        def.setText("\n Para 3 eventos A,B,C:"
                + "\n\n P(AUBUC) = P(A) + P(B) + P(C) - P(AnB) - P(AnC) - P(BnC) +"
                + "\n P(AnBnC)\n"
                + "\n Este teorema nos ayuda a calcular la probabilidad de que ocurra "
                + "\n A,B,C ");
        ejem.setText("\n Los estudiantes utilizan tres colores de lapiceros, azul negro y "
                + "\n rojo, 0.3, 0.2, y 0.5 respectivamente, la probabilidad de que "
                + "\n utilicen azul y negro es de 0.1, que utilicen azul y rojo 0.05,"
                + "\n la probabilidad de que utilicen negro y rojo es de 0.06, y la "
                + "\n probabilidad de que utilicen los tres colores es de 0.01."
                + "\n ¿Calcule la probabilidad de que un estudiante utilice alguno de "
                + "\n estos colores. "
                + "\n\n  Datos."
                + "\n    P(A) = 0.3"
                + "\n    P(N) = 0.2"
                + "\n    P(R) = 0.15"
                + "\n    P(AnN) = 0.1"
                + "\n    P(AnR) = 0.05"
                + "\n    P(NnR) = 0.06"
                + "\n    P(AnNnR) = 0.01");
        this.escala(imejem, "src/imres/TEO8.png");
        this.escala(formula, "src/formulas/f8.png");
               uno.setText(" P(A) "); unoa.setText("");
               dos.setText(" P(B) "); dosa.setText("");
               tres.setText(" P(C) "); tresa.setText("");
               cuatro.setText(" -P(AnB) "); cuatroa.setText("");
               cinco.setText(" -P(AnC) "); cincoa.setText("");
               seis.setText(" -P(BnC) "); seisa.setText("");
               siete.setText(" P(AnBnC) "); sietea.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(true);   tresa.setVisible(true);
       cuatro.setVisible(true); cuatroa.setVisible(true);
       cinco.setVisible(true);  cincoa.setVisible(true);
       seis.setVisible(true);   seisa.setVisible(true);
       siete.setVisible(true);  sietea.setVisible(true);
       activar(7);
    }//GEN-LAST:event_te8MouseClicked

    private void te9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te9MouseClicked
    titulo.setText("Teorema 9");
    def.setText("\n A y A' son eventos complementarios entonces:"
            + "\n\n         P(A´) = 1 - P(A)\n"
            + "\n Este teorema nos ayuda a calcular la no ocurrencia de un evento.");
    ejem.setText("\n Encuentre la probabilidad de que al momento de lanzar un "
            + "\n dado no salga como resultado 1, siendo 0.17 la probabilidad de "
            + "\n que salga 1."
            + "\n\n  Datos."
            + "\n    P(A) = 0.17");
    this.escala(imejem, "src/imres/TEO9.png");
    this.escala(formula, "src/formulas/f9.png");
       uno.setText(" P(A) "); unoa.setText("");
       dos.setVisible(false);    dosa.setVisible(false);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(8);
    }//GEN-LAST:event_te9MouseClicked

    private void te10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te10MouseClicked
    titulo.setText("Teorema 10");
    def.setText("Si en un experimento pueden ocurrir los eventos A y B entonces:"
            + "\n\n P = P(A) * P(A|B)\n"
            + "\n Este teorema nos ayuda a calcular la probabilidad de que ocurran "
            + "\n dos eventos.");
    ejem.setText("\n Una caja de 10 lapiceros de los cuales 5 son rojos y 5 son negros. "
            + "\n ¿Calcule es la probabilidad de que saque 2 lapiceros uno despues del "
            + "\n otro (sin reemplazarlo), estos sean de color rojo."
            + "\n\n  Datos."
            + "\n    P(A) = 0.5"
            + "\n    P(B) = 0.44");
    this.escala(imejem, "src/imres/TEO10.png");
    this.escala(formula, "src/formulas/f10.png");
    uno.setText(" P(A) "); unoa.setText("");
    dos.setText(" P(B|A) "); dosa.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(9);
       
    }//GEN-LAST:event_te10MouseClicked

    private void te11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_te11MouseClicked
        titulo.setText("Teorema 11");
        def.setText("\n Dos eventos A y B son independientes si y solo si:"
                + "\n\n P(AnB) = P(A) * P(B)\n"
                + "\n Este teorema nos ayuda a calcular 2 eventos independientes.");
        ejem.setText("\n La probabilidad de que hoy sea un día nublado es de 0.98,"
                + "\n y la probabilidad de que hoy no realice tareas es de 0.92."
                + "\n Calcule la probabilidad de que hoy sea un día nublado y que "
                + "\n no realice ninguna tarea."
                + "\n\n  Datos."
                + "\n    P(A) = 0.98"
                + "\n    P(B) = 0.92");
        this.escala(imejem, "src/imres/TE11.png");
        this.escala(formula, "src/formulas/f11.png");
        uno.setText(" P(A) "); unoa.setText("");
        dos.setText(" P(B) "); dosa.setText("");
       dos.setVisible(true);    dosa.setVisible(true);
       tres.setVisible(false);   tresa.setVisible(false);
       cuatro.setVisible(false); cuatroa.setVisible(false);
       cinco.setVisible(false);  cincoa.setVisible(false);
       seis.setVisible(false);   seisa.setVisible(false);
       siete.setVisible(false);  sietea.setVisible(false);
       activar(10);
    }//GEN-LAST:event_te11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tresaActionPerformed

    private void cincoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cincoaActionPerformed

    private void seisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seisaActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        op2();
    }//GEN-LAST:event_mostrarActionPerformed

    private void dosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }
    
    private void escala (JLabel imagen, String direccion){
       this.im =new ImageIcon(direccion);
       this.icono = new ImageIcon(
               this.im.getImage().getScaledInstance(
                       imagen.getWidth(), 
                       imagen.getHeight(), 
                       Image.SCALE_DEFAULT));
     imagen.setIcon(this.icono);
     this.repaint();
     
        
    }

    private int factorial(int num){
       int factorial=1;
        for(int i = num;i>0;i--){
            factorial*=i;
        }
       
       return factorial;
    }
    
    private void activar(int ap){
        for(int i =0;i<op.length;i++){
            op[i]=0;
        }
        op[ap]=1;
    }
    
    private void op2(){
         int a1=0, a2=0, a3=0, a4=0, a5=0, a6=0,a7=0,a8=0,res=0;
         float b1=0,b2=0,b3=0,b4=0,b5=0,b6=0,b7=0,res1=0;
     int indice=0;
     for(int y=0;y<op.length;y++){
         if(op[y]==1){
             indice=y;
         }
     }
     
     switch(indice){
         
  
         case 0:a1=Integer.parseInt(unoa.getText());
         if(a1>0){
             res=factorial(a1);
             resultado.setText(Integer.toString(res));
         }else{
             JOptionPane.showMessageDialog(null, "Debe ingresar valores positivos");
         }
             
                 break;
         case 1: a1=Integer.parseInt(unoa.getText());
                 a2=Integer.parseInt(dosa.getText());
                 if(a1>0 && a2>0){
                     a3=a1-a2;
                 res=factorial(a1)/factorial(a3);
                 resultado.setText(Integer.toString(res));
                 }else{
                     JOptionPane.showMessageDialog(null, "Debe ingresar valores positivos");
                 }
                 break;
         case 2: a1=Integer.parseInt(unoa.getText());
         if(a1>0){
             res = factorial(a1-1);
                 resultado.setText(Integer.toString(res));
         }else{
             JOptionPane.showMessageDialog(null, "Debe ingresar valores positivos");
         }
                 break;
         case 3: a1 = Integer.parseInt(unoa.getText());
                a2 = Integer.parseInt(dosa.getText());
                a3 = Integer.parseInt(tresa.getText());
                a4 = Integer.parseInt(cuatroa.getText());
                a5 = Integer.parseInt(cincoa.getText());
                a6 = Integer.parseInt(seisa.getText());
                a7 = Integer.parseInt(sietea.getText());
                a8 = (((((a2+a3)+a4)+a5)+a6)+a7);
                if(a8==a1){
                    a1=factorial(Integer.parseInt(unoa.getText()));
                a2=factorial(Integer.parseInt(dosa.getText()));
                a3=factorial(Integer.parseInt(tresa.getText()));
                a4=factorial(Integer.parseInt(cuatroa.getText()));
                a5=factorial(Integer.parseInt(cincoa.getText()));
                a6=factorial(Integer.parseInt(seisa.getText()));
                a7=factorial(Integer.parseInt(sietea.getText()));
                res= a1/(a2*a3*a4*a5*a6*a7);
                resultado.setText(Integer.toString(res));
                }else{
                    JOptionPane.showMessageDialog(null,"No se puede realizr el calculo"
                            + "\n La sumatoria de todas las sub-n debe ser igual a n");
                }

                break;
         case 4:a1 = Integer.parseInt(unoa.getText());
                a2 = Integer.parseInt(dosa.getText());
                a3 = Integer.parseInt(tresa.getText());
                a4 = Integer.parseInt(cuatroa.getText());
                a5 = Integer.parseInt(cincoa.getText());
                a6 = Integer.parseInt(seisa.getText());
                a7 = Integer.parseInt(sietea.getText());
                a8 = (((((a2+a3)+a4)+a5)+a6)+a7);
                if(a8==a1){
                    a1=factorial(Integer.parseInt(unoa.getText()));
                a2=factorial(Integer.parseInt(dosa.getText()));
                a3=factorial(Integer.parseInt(tresa.getText()));
                a4=factorial(Integer.parseInt(cuatroa.getText()));
                a5=factorial(Integer.parseInt(cincoa.getText()));
                a6=factorial(Integer.parseInt(seisa.getText()));
                a7=factorial(Integer.parseInt(sietea.getText()));
                res= a1/(a2*a3*a4*a5*a6*a7);
                resultado.setText(Integer.toString(res));
                }else{
                    JOptionPane.showMessageDialog(null,"No se puede realizar el cálculo"
                            + "\n La sumatoria de todas las sub-n debe ser igual a n");
                }

                break;
         case 5: a1=Integer.parseInt(unoa.getText());
                 a2=Integer.parseInt(dosa.getText());
                 a3=(a1-a2);
                 res=factorial(a1)/(factorial(a2)*factorial(a3));
                 resultado.setText(Integer.toString(res));
                 break;
         case 6: b1 = Float.parseFloat(unoa.getText());
                 b2 = Float.parseFloat(dosa.getText());
                 b3 = Float.parseFloat(tresa.getText());
                 if(b1>0 && b2>0 && b3>0){
                     if(b1<1 && b2<1 && b3<1){
                        res1 = ((b1+b2)-b3);
                 resultado.setText(Float.toString(res1)); 
                     }else{
                         JOptionPane.showMessageDialog(null,"La probabilidad debe ser menor a 1");
                     }
                 }else{
                     JOptionPane.showMessageDialog(null,"La probabilidad debe ser mayor a 0");
                 }
                 break;
         case 7: b1 = Float.parseFloat(unoa.getText());
                 b2 = Float.parseFloat(dosa.getText());
                 b3 = Float.parseFloat(tresa.getText());
                 b4 = Float.parseFloat(cuatroa.getText());
                 b5 = Float.parseFloat(cincoa.getText());
                 b6 = Float.parseFloat(seisa.getText());
                 b7 = Float.parseFloat(sietea.getText());
                 if(b1>0 && b2>0 && b3>0 && b4>0 && b5>0 && b6>0 && b7>0){
                     if(b1<1 && b2<1 && b3<1 && b4<1 && b5<1 && b6<1 && b7<1){
                     res1 = (((b1+b2+b3)-(b4+b5+b6))+b7);
                 resultado.setText(Float.toString(res1));
                 }else
                         JOptionPane.showMessageDialog(null,"La probabilidad debe ser menor a 1");
                 }else{
                  JOptionPane.showMessageDialog(null,"La probabilidad debe ser mayor a 0");   
                 }
                 break;
         case 8: b1 = Float.parseFloat(unoa.getText());
                    if(b1>0){
                        if(b1<1){
                            res1 = (1-b1);
                 resultado.setText(Float.toString(res1));
                        }else{
                            JOptionPane.showMessageDialog(null,"La probabilidad debe ser menor a 1");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"La probabilidad debe ser mayor a 0");   
                    }
                break;
         case 9: b1 = Float.parseFloat(unoa.getText());
                 b2 = Float.parseFloat(dosa.getText());
                 if(b1>0&&b2>0){
                     if(b1<1&&b2<2){
                         res1 = (b1*b2);
                 resultado.setText(Float.toString(res1));   
                     }  else{
                         JOptionPane.showMessageDialog(null,"La probabilidad debe ser menor a 1");
                     }
                 }else{
                     JOptionPane.showMessageDialog(null,"La probabilidad debe ser mayor a 0");   
                 }
                 break;
         case 10: b1 = Float.parseFloat(unoa.getText());
                  b2 = Float.parseFloat(dosa.getText());
                  if(b1>0&&b2>0){
                      if(b1<1&&b2<1){
                       res1 = (b1*b2);
                  resultado.setText(Float.toString(res1));  
                      }else{
                          JOptionPane.showMessageDialog(null,"La probabilidad debe ser menor a 1");
                      }
                  }else{
                      JOptionPane.showMessageDialog(null, "La probabilidad debe ser mayor a 0");
                  }
                      
     }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cinco;
    private javax.swing.JTextField cincoa;
    private javax.swing.JLabel cuatro;
    private javax.swing.JTextField cuatroa;
    private javax.swing.JTextArea def;
    private javax.swing.JLabel defiición1;
    private javax.swing.JLabel dos;
    private javax.swing.JTextField dosa;
    private javax.swing.JTextArea ejem;
    private javax.swing.JLabel ejemplo1;
    private javax.swing.JLabel formula;
    private javax.swing.JLabel imejem;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane lhgds;
    private javax.swing.JButton mostrar;
    private javax.swing.JLabel panelcalculadora;
    private javax.swing.JLabel prueba;
    private javax.swing.JTextField resultado;
    private javax.swing.JLabel seis;
    private javax.swing.JTextField seisa;
    private javax.swing.JLabel siete;
    private javax.swing.JTextField sietea;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel te1;
    private javax.swing.JLabel te10;
    private javax.swing.JLabel te11;
    private javax.swing.JLabel te13;
    private javax.swing.JLabel te14;
    private javax.swing.JLabel te15;
    private javax.swing.JLabel te16;
    private javax.swing.JLabel te17;
    private javax.swing.JLabel te18;
    private javax.swing.JLabel te19;
    private javax.swing.JLabel te2;
    private javax.swing.JLabel te20;
    private javax.swing.JLabel te3;
    private javax.swing.JLabel te4;
    private javax.swing.JLabel te5;
    private javax.swing.JLabel te6;
    private javax.swing.JLabel te7;
    private javax.swing.JLabel te8;
    private javax.swing.JLabel te9;
    private javax.swing.JLabel tit;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel tres;
    private javax.swing.JTextField tresa;
    private javax.swing.JLabel uno;
    private javax.swing.JTextField unoa;
    // End of variables declaration//GEN-END:variables

    private void escala(JPanel teoremas, String srcimagenesmoradopng) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
